# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{rspec-am}
  s.version = "0.4.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["MarcoRibi"]
  s.date = %q{2010-08-02}
  s.description = %q{This gem provides some simple association matchers if you write tests with Rspec}
  s.email = %q{marco@software-lab.ch}
  s.extra_rdoc_files = [
    "LICENSE",
     "README.markdown"
  ]
  s.files = [
    ".document",
     ".gitignore",
     "LICENSE",
     "README.markdown",
     "Rakefile",
     "VERSION",
     "lib/rspec-am.rb",
     "lib/rspec-am/belong_to.rb",
     "lib/rspec-am/have_many.rb",
     "lib/rspec-am/have_one.rb",
     "rspec-am.gemspec",
     "spec/belong_to_spec.rb",
     "spec/fake_data.rb",
     "spec/have_many_spec.rb",
     "spec/have_one_spec.rb",
     "spec/spec.opts",
     "spec/spec_helper.rb"
  ]
  s.homepage = %q{http://github.com/marcoribi/rspec-am}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{This gem provides some simple association matchers if you write tests with Rspec}
  s.test_files = [
    "spec/belong_to_spec.rb",
     "spec/fake_data.rb",
     "spec/have_many_spec.rb",
     "spec/have_one_spec.rb",
     "spec/spec_helper.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<rspec>, [">= 0"])
      s.add_development_dependency(%q<rails>, [">= 0"])
    else
      s.add_dependency(%q<rspec>, [">= 0"])
      s.add_dependency(%q<rails>, [">= 0"])
    end
  else
    s.add_dependency(%q<rspec>, [">= 0"])
    s.add_dependency(%q<rails>, [">= 0"])
  end
end

